{{- if .Values.security.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "findag.fullname" . }}
  labels:
    {{- include "findag.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "findag.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow HTTP traffic from ingress controllers
    - from:
        - namespaceSelector:
            matchLabels:
              name: ingress-nginx
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
        - protocol: TCP
          port: {{ .Values.service.apiPort }}
    # Allow metrics scraping from monitoring
    - from:
        - namespaceSelector:
            matchLabels:
              name: monitoring
      ports:
        - protocol: TCP
          port: {{ .Values.service.metricsPort }}
    # Allow P2P communication between FinDAG nodes
    - from:
        - podSelector:
            matchLabels:
              {{- include "findag.selectorLabels" . | nindent 14 }}
      ports:
        - protocol: TCP
          port: {{ .Values.config.network.p2pPort }}
  egress:
    # Allow DNS resolution
    - to: []
      ports:
        - protocol: UDP
          port: 53
    # Allow HTTP/HTTPS for external API calls
    - to: []
      ports:
        - protocol: TCP
          port: 80
        - protocol: TCP
          port: 443
    # Allow P2P communication to other FinDAG nodes
    - to:
        - podSelector:
            matchLabels:
              {{- include "findag.selectorLabels" . | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.config.network.p2pPort }}
    {{- if .Values.postgresql.enabled }}
    # Allow database access
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: postgresql
      ports:
        - protocol: TCP
          port: 5432
    {{- end }}
    {{- if .Values.redis.enabled }}
    # Allow Redis access
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: redis
      ports:
        - protocol: TCP
          port: 6379
    {{- end }}
{{- end }} 