apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: findag-data-pvc
  namespace: findag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: findag-logs-pvc
  namespace: findag
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard 