apiVersion: v1
kind: Secret
metadata:
  name: findag-secrets
  namespace: findag
type: Opaque
data:
  # Base64 encoded values - change these in production!
  admin-username: YWRtaW4=  # admin
  admin-password-hash: NWU4ODQ4OThkYTI4MDQ3MTUxZDBlNTZmOGRjNjI5Mjc3MzYwM2QwZDZhYWJiZGQ2MmExMWVmNzIxZDE1NDJkOA==  # 5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8
  jwt-secret: eW91cl9qd3Rfc2VjcmV0X2hlcmVfY2hhbmdlX2luX3Byb2R1Y3Rpb24=  # your_jwt_secret_here_change_in_production
stringData:
  # Non-base64 values for easier reading
  audit-log-path: /app/logs/audit.log
  cors-allowed-origins: "*"
  cors-allowed-methods: "GET,POST,DELETE"
  cors-allowed-headers: "Authorization,Content-Type" 