# Default values for findag
# This is a YAML-formatted file.

replicaCount: 3

image:
  repository: ghcr.io/your-org/findag
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 3000
  apiPort: 8080
  metricsPort: 9898

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: findag.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: findag-tls
  #    hosts:
  #      - findag.local

resources:
  limits:
    cpu: 2000m
    memory: 4Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - findag
        topologyKey: kubernetes.io/hostname

# FinDAG specific configuration
config:
  # Network configuration
  network:
    port: 3000
    apiPort: 8080
    metricsPort: 9898
    p2pPort: 9000
    
  # Consensus configuration
  consensus:
    roundInterval: 100  # milliseconds
    maxRoundsPerEpoch: 1000
    quorumSize: 2
    
  # Storage configuration
  storage:
    dataDir: "/app/data"
    backupEnabled: true
    backupInterval: "1h"
    
  # Security configuration
  security:
    jwtSecret: ""
    apiKeyRequired: true
    rateLimitEnabled: true
    maxRequestsPerMinute: 1000

# Persistence configuration
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi

# Monitoring and observability
monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
  grafana:
    enabled: false
    dashboard:
      enabled: false

# Database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: ""
    database: "findag"
  primary:
    persistence:
      enabled: true
      size: 8Gi
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 250m
        memory: 512Mi

# Redis configuration (for caching and session storage)
redis:
  enabled: true
  auth:
    enabled: false
  master:
    persistence:
      enabled: true
      size: 2Gi
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi

# Backup configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: 7  # days
  storage:
    type: "s3"  # or "local"
    bucket: "findag-backups"
    region: "us-west-2"

# Security and compliance
security:
  podSecurityPolicy:
    enabled: false
  networkPolicy:
    enabled: true
  secrets:
    create: true
    jwtSecret: ""
    apiKeys: [] 